### ISSUE TITLE
Blender 2.80 Beta - VTF Import Addon Installation

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/io_texture_VTF#2]
Blender 2.80 Beta Win64 Hash: 9149e894210 (2018-12-16 23:25)

I downloaded the latest 2.80 version: 
- https://github.com/REDxEYE/io_texture_VTF/archive/blender2.80.zip
- latest commit ad621e2 (a day ago)

I tried installing via zip file, but the add-on doesn't appear in the list. 
All categories are highlighted: Official, Community, Testing
This appeared in the console after attempting to install:
Modules Installed () from 'D:\\Blender\\Blender Addons\\VTF Importer\\20181219_2-80\\io_texture_VTF-blender2.80.zip' into 'C:\\Users\\User\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'

I had no problems installing and activating the latest SourceMDL add-on in Blender 2.80 beta.

**Comment by REDxEYE** [comment]
.80 in folder name breaks blender addon utils

**Comment by REDxEYE** [comment]
I changed name if Blender 2.8 branch so it now work properly
